-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 03:14:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sedt2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sedt2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sedt2` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;
USE `sedt2` ;

-- -----------------------------------------------------
-- Table `sedt2`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt2`.`grupo` (
  `idgrupo` INT NOT NULL,
  `nombreequipo` VARCHAR(45) NULL DEFAULT NULL,
  `supervisor_idsupervisor1` INT NOT NULL,
  `funciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `fk_grupo_supervisor1_idx` (`supervisor_idsupervisor1` ASC) ,
  CONSTRAINT `fk_grupo_supervisor1`
    FOREIGN KEY (`supervisor_idsupervisor1`)
    REFERENCES `mydb`.`supervisor` (`idsupervisor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sedt2`.`metrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt2`.`metrica` (
  `idmetrica` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `medicion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmetrica`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sedt2`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt2`.`persona` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `puesto` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(45) NULL DEFAULT NULL,
  `supervisor` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sedt2`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt2`.`objetivo` (
  `idobjetivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `porcentaje` FLOAT NULL DEFAULT NULL,
  `persona` INT NOT NULL,
  `id_metrica` INT NOT NULL,
  `fechainicio` VARCHAR(45) NULL DEFAULT NULL,
  `fechafin` VARCHAR(45) NULL DEFAULT NULL,
  `meta` VARCHAR(45) NULL DEFAULT NULL,
  `aceptable` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idobjetivo`),
  INDEX `fk_objetivo_persona_idx` (`persona` ASC) ,
  INDEX `fk_objetivo_metrica_idx` (`id_metrica` ASC) ,
  CONSTRAINT `fk_objetivo_metrica`
    FOREIGN KEY (`id_metrica`)
    REFERENCES `sedt2`.`metrica` (`idmetrica`),
  CONSTRAINT `fk_objetivo_persona`
    FOREIGN KEY (`persona`)
    REFERENCES `sedt2`.`persona` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sedt2`.`progreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt2`.`progreso` (
  `idprogreso` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL DEFAULT NULL,
  `porcentaje` FLOAT NULL DEFAULT NULL,
  `idobjetivo` INT NOT NULL,
  `descripcion` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`idprogreso`),
  INDEX `fk_progreso_objetivo` (`idobjetivo` ASC) ,
  CONSTRAINT `fk_progreso_objetivo`
    FOREIGN KEY (`idobjetivo`)
    REFERENCES `sedt2`.`objetivo` (`idobjetivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;

USE `sedt2` ;

-- -----------------------------------------------------
-- procedure sumar
-- -----------------------------------------------------

DELIMITER $$
USE `sedt2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sumar`(in A int, in id int )
BEGIN
	declare suma int; 
    set suma = (
		select porcentaje from objetivo where idobjetivo = id 
    );
    update objetivo set porcentaje = suma + A where idobjetivo = id; 
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
